title       = "Cryptography"
related     = ["tls", "compression"]

[entry.octavo]

[entry.openssl]

[entry.ring]
crates_io_id = false
repository_url = "https://github.com/briansmith/ring"

[entry.rust-crypto]

[entry.sodiumoxide]
