title       = "Database Bindings"
related     = ["databases", "orm", "http-servers"]

[entry.cassandra]

[entry.couchdb]

[entry.etcd]

[entry.lmdb-rs]

[entry.mongodb]

[entry.mysql]

[entry.postgres]

[entry.redis]

[entry.rusqlite]

[entry.rust-sqlite]

[entry.rs-es]

[entry.sherwood]
crates_io_id = false
repository_url = "https://github.com/vhbit/sherwood"
licence = "MIT"

[entry.sqlite3]
crates_io_id = false
name = "Rust-Sqlite3"
repository_url = "https://github.com/dckc/rust-sqlite3"
licence = "MIT"
