title       = "Games"
related     = ["gaming-console-emulators"]

[entry.rocket]

[entry.rust-sudoku]

[entry.snake-piston]

[entry.rust-2048]

[entry.rust-lightsout]

[entry.rust-pong]

[entry.pong-rs]

[entry.rust-snake]

[entry.rusty-tetris]

[entry.r_tetris]

[entry.rtetris]

[entry.tetris-piston]

[entry.game-of-life]

[entry.snake]

[entry.hematite]

[entry.playform-server]

[entry.rustyhex]

[entry.seabirdsbreakfast]

[entry.colonize]

[entry.minesweeper-rs]

[entry.puzzlefighter]

[entry.angolmois]

[entry.sokoban-rs]

[entry.zoc]


