title       = "Geospatial Tools"
related     = ["text-editors", "development-tools", "ide"]

[entry.gdal]

[entry.geo]

[entry.geocoding]

[entry.geohash]

[entry.geojson]

[entry.gpx]

[entry.osm]

[entry.proj]

[entry.shapefile]

[entry.topojson]
crates_io_id = false
repository_url = "https://github.com/georust/rust-topojson"
licence = "MIT"

[entry.wkt]

[entry.world-file]
