title       = "Operating Systems"
related     = ["text-editors", "development-tools", "ide"]

[entry.redox]
crates_io_id = false
repository_url = "https://github.com/redox-os/redox"
homepage_url = "http://www.redox-os.org/"
licence = "MIT"
