title       = "Web Frameworks"
group       = "Web"
description = "Web frameworks in Rust"
related     = ["http-servers", "mysql-drivers"]

[entry.conduit]

[entry.iron]

[entry.rustful]

[entry.nickel]
